### ISSUE TITLE
Repository comments

### ISSUE THREAD

**Issue by solnavss** [bc-anaisabel/juniperus_paper#17]
Hi, I have some comments that I hope will help you to improve your repo:
- [x] Add open-source license (https://choosealicense.com/)
- [x] Add more references in the Introduction
- [x] Separate the code that belongs to the networks analysis from the script "3_Juniperus_Beta_Diversity.R"

**Comment by AliciaMstt** [comment]
In addtion to Sol comments, I think it would be useful if you could attend the following comments:

README:
- [x]  Add to your README which primers were used  
- [x] Columns of all metadata files should be briefly explained in the data README. For instance what is `Pdis`, `Nit` and `CN`? but also even the obvious ones, like `Mg` and `Na`, should be explained. When relevant, include in this short explanation what are the units.
- [x] Better describe the content of the /output directory so that at least we know with which script was each figure done.
- [x] The section "Raw data" of your README should go earlier, maybe just before /data.
- [x] The "Citation" at the end of a README should refer to how to cite the work of the repository you are looking at. Palmer et al 2018, doesn't seem to be the citation of your work, but a reference. If this is the case, change "Citation" for "References" and mention Palmer's publication somewhere in your README.

Repo organization:
- [x] All your scripts and manual steps should be numbered, currently it is confusing because only your R scripts are numbered, but they are not the first steps.
- [x] In your data directory, there are files that are not mentioned in the README. For instance `network_df.csv`. Either mention or delete them.


Scripts:
- [x] in the comments of the script `amptk_for_illumina.sh` name the steps as in `AMPtk_pipeline.md` so that it is easier to follow both documents together.
- [x] Your R scripts don't seem to use all the libraries that are called at the beginning. Please only include the libraries that are truly used.
- [x] Script `1_Filter_otu_table.R` line 251: your comment says "multiply by 1000" but the code line doesn't seem to do this. Also, explain how you chose this number to multiply.
- [x] Script `2_Juniperus_Alpha_Diversity.R` needs clearer documentation (comments). Also, either there or somewhere in the README explain what does the acronyms of the Trophic category mean. 
- [x] Script `3_Juniperus_Beta_Diversity.R`needs clearer documentation. There are several steps that need to be briefly commented so that anyone can follow what are you doing and why.

**Comment by bc-anaisabel** [comment]
> Hi, I have some comments that I hope will help you to improve your repo:
> 
>     * [ ]  Add open-source license (https://choosealicense.com/)
> 
>     * [ ]  Add more references in the Introduction
> 
>     * [x]  Separate the code that belongs to the networks analysis from the script "3_Juniperus_Beta_Diversity.R"

Hi Marisol @solouli  About item number 1 on the list. Could you explain a bit, I am confused about the type of license I would need? These are data that will soon be sent to try to get them published, so I am unsure. I do want to share the code.

**Comment by solnavss** [comment]
Hi, Ana @bc-anaisabel The goal of the task is for you to check all the license types that exist for different projects. In my opinion, the most appropriate license, since we have code and want to share it but keeping copyright is MIT's. "The MIT License is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions", you can read about it [here](https://choosealicense.com/licenses/mit/). I believe the issue with the "soon to be published data" is independent if you are referencing the authors to get access or the other case if you reference the database (Eg. Genbank).

**Comment by bc-anaisabel** [comment]
Thank you @solouli. I reviewed the license types but to be honest I don't quite get all of them. I can see how the MIT one could fit this type of project though. However I noticed the pipeline I used to obtain my clean data has a github repo with a [license](https://github.com/nextgenusfs/amptk/blob/master/LICENSE.md) already, since much of this had not been possible without that part I am using their same license. But again not sure if this is how it should work. I'll ask on class either way. Thanks!
