### ISSUE TITLE
archive should not be in github

### ISSUE THREAD

**Issue by AliciaMstt** [bc-anaisabel/juniperus_paper#8]
This directory is useful for your records, but it is not good practice to upload it to github. You can take it out of your repo or just add it to your gitignore list.

**Comment by bc-anaisabel** [comment]
I add it to my .gitignore list. Since this was an already tracked directory and all files were already committed in my repository what I did was unstage them: 

`git rm -r --cached some-directory`

create a commit: 
`git commit -m 'Remove the now ignored directory "some-directory"'`

and push that to GitHub:
`git push origin master`
